version: '3.7'
services:
  keygen_app:
    container_name: keygen_app
    build: ./dist
    networks:
      nginx_net:
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app

networks:
  nginx_net:
    external: true