version: '3.7'
services:
  keygen_app:
    container_name: keygen_app
    build: ./dist
    restart: unless-stopped
    ports:
      - 8080:5000
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    volumes:
      - ./dist:/app
    
networks:
  default:
    external:
      name: nginx-proxy